import tasfile
import typing

class TasFile:
    def append(self, /, count: int, delta_time: float) -> typing.Any: ...
    def batchly_clear_key_pressed(self, /, index_from: int, index_to: int) -> typing.Any: ...
    def batchly_flip_key_pressed(self, /, index_from: int, index_to: int, key: tasfile.TasKey) -> typing.Any: ...
    def batchly_set_delta_time(self, /, index_from: int, index_to: int, delta_time: float) -> typing.Any: ...
    def batchly_set_key_pressed(self, /, index_from: int, index_to: int, key: tasfile.TasKey, pressed: bool) -> typing.Any: ...
    def clear(self, /) -> typing.Any: ...
    def clear_key_pressed(self, /, index: int) -> typing.Any: ...
    def flip_key_pressed(self, /, index: int, key: tasfile.TasKey) -> typing.Any: ...
    def get_count(self, /) -> int: ...
    def get_delta_time(self, /, index: int) -> float: ...
    def insert(self, /, index: int, count: int, delta_time: float) -> typing.Any: ...
    def is_empty(self, /) -> bool: ...
    def is_key_pressed(self, /, index: int, key: tasfile.TasKey) -> bool: ...
    def remove(self, /, index_from: int, index_to: int) -> typing.Any: ...
    def set_delta_time(self, /, index: int, delta_time: float) -> typing.Any: ...
    def set_key_pressed(self, /, index: int, key: tasfile.TasKey, pressed: bool) -> typing.Any: ...

class TasKey:
    def __eq__(self, /, other: TasKey | int) -> bool: ...
    def __ne__(self, /, other: TasKey | int) -> bool: ...

def create(count: int, delta_time: float) -> tasfile.TasFile: ...
def load(filename: str) -> tasfile.TasFile: ...
def save(file: tasfile.TasFile, filename: str) -> typing.Any: ...
