[project]
name = "blctas"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[build-system]
requires = ["maturin>=1.11,<2.0"]
build-backend = "maturin"

[tool.maturin]
binding = "pyo3"
python-source = "python"
manifest-path = "rust/Cargo.toml"
module-name = "blctas._blctas"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "sphinx>=7.1.2",
]
